jobs:
 - name: daily
   targetName: dev 
   schedule: 0 12 * * * 
   steps:
     - name: run models 
       command: dbt_gnm run
     - name: test models
       command: dbt_gnm test

 - name: nightly
   schedule: 0 0 * * * 
   steps:
     - name: run models
       command: dbt_gnm run

